### ISSUE TITLE
[Bug] wrong detect fields names

### ISSUE THREAD

**Issue by flame0** [LindsayBradford/go-dbf#12]
For example when i am trying to get filed name, I expect to receive filed "**REGN**" in byte representation = [52 45 47 4E]. But i get something like "**REGN uO**" [5245474E 00157505 4F].

**Comment by mygoodboy** [comment]
package main

import (
	"fmt"
	"github.com/LindsayBradford/go-dbf/godbf"
)

func main() {
	// dbfTable, _ := godbf.NewFromFile("ChangeToYourDBF.dbf", "UTF8")
	dbfTable, _ := godbf.NewFromFile("testpro.dbf", "Big5")
	FieldsName := dbfTable.FieldNames()

	for i := 0; i < dbfTable.NumberOfRecords(); i++ {

		fmt.Printf("#%d", i)
		for j := 0; j < len(FieldsName); j++ {

			val, _ := dbfTable.FieldValueByName(i, FieldsName[j])
			fmt.Printf(" %s=%s ,", FieldsName[j], val)
		}
		fmt.Printf("\n")
	}
}

**Comment by LindsayBradford** [comment]
Strictly speaking, the [file standard I use as reference](https://en.wikipedia.org/wiki/.dbf#File_format_of_Level_5_DOS_dBASE) only supports ASCII character encoding.  I do go to the effort of supporting UTF-8, given its lineage with ASCII, but I won't be chasing issues with encodings such as Big5, which is where I suspect your problem lies here.  If you can supply some code test showing this kind of failure with ascii or utf-8, I'll chase it for those.
