### ISSUE TITLE
Add ability to create dbf table from byte array

### ISSUE THREAD

**Issue by GoogleCodeExporter** [LindsayBradford/go-dbf#5]
```
I am wanting to use go-dbf to parse a dbf file on the web without saving it on 
to the machine. I have looked through the source code and I think this would be 
possible with some refactoring. I could go ahead and propose something, but I 
haven't worked with mercurial before so don't know how contributing works.
```

Original issue reported on code.google.com by `ski.rodr...@gmail.com` on 30 Jul 2014 at 12:13

**Comment by LindsayBradford** [comment]
Hi Pedro. 

I hadn't realised you'd taken a fork and added URL reading code (failure in notifications, at a guess).  Recently, I noticed that there were open issues in the go-dbf GitHub repository I'd not seen before, and saw that your (stalled) contribution as an open issue. 

I'm guessing the easiest thing to do from here is to fork from my github repository on the 2d1196663b9d commit (under github, it's now commit  3063e20f43cb3c68aaddce517e62889c7bd4830), re-apply your changes and  and send me a pull request for your  google-code 00283c9e6f76 commit.   I'm proposing this because the git history was re-done through the google.code -> github transfer.   

Alternatively, I can always take that commit from google code, and manually merge myself.  I guess it boils down to how you'd like your name associated with your contribution. The pull-request route would see you very obviously as a contributor. 

Let me know how you'd like this to swing.


thanks and regards,

Linds.

**Comment by EntilZha** [comment]
Hi Lindsay,

Took me a little to remember some of the code. It doesn't look like too much trouble to make an actual pull request. Just to make sure:

1. Fork (this) github repository
2. What commit would I check out here, the first or the second?
3. Manually reapply changes (copy paste file, since I don't actually recall what changes I made)
4. Make pull request.

**Comment by LindsayBradford** [comment]
Hey Pedro,

The commit that matches the google-code one you based your changes on is linked below:

https://github.com/LindsayBradford/go-dbf/commit/d3063e20f43cb3c68aaddce517e62889c7bd4830

So, basically:

1) Yes, fork this repository
2) Create a new branch at the above d3063e commit.
3) re-apply your changes to the new branch, and yes, it looks like a copy-paste will be fine. 
4) make a pull-request for the changes committed to that new branch. 

I'll have a merge issue to deal with once I accept the pull request.

Also, caveat lector... I've not tried this before. In theory it should work. ;)

Linds.

**Comment by LindsayBradford** [comment]
See [this pull request](https://github.com/LindsayBradford/go-dbf/pull/9).
